name: Update Readme
on:
  schedule:
    # Runs every day
    - cron: "35 5 * * 1"
  workflow_dispatch:
jobs:
  update:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://mahyarmirrashed.com/atom.xml
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "docs: update readme with blog posts"
      - uses: mahyarmirrashed/github-readme-stats@v2.0
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TIMEZONE: "America/Winnipeg"
          FEATURES: "DAY_STATS,WEEK_STATS"
      - name: "Commit changes"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update readme via actions"
          git push
